# Generated by Django 6.1.1 on 2026-09-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_added_permissions_order_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
